alpha_number_of_sampled_points: 5000
azure_messaging_connectionstring: Endpoint=sb://messagingpipeline.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=yd4DxLLNyHoYZQGQ/RmYP3uZvDggm1RmBQuI7WUyGGY=
azure_storage_connectionstring: DefaultEndpointsProtocol=https;AccountName=pipelinestorageazu;AccountKey=J6QLmIIoKg5qG9LM5OeUS4yGjzS77NMTnaTCLk3ayT/iiioE++OaNHi5OMvgjgnm3uZsonfM6Z4L+AStnCUmFQ==;EndpointSuffix=core.windows.net
b: 6
complete: 'True'
container_name: container
d: 6
max_runs: 5
mode: ml
n: 10
points: 4000
queue_name: queue
r: 4
s: 12
save_folder: download
slice_variations: 0
v: 6
wait_time: 60
