alpha_number_of_sampled_points: 5000
azure_messaging_connectionstring: Endpoint=sb://messagingpipeline.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=yd4DxLLNyHoYZQGQ/RmYP3uZvDggm1RmBQuI7WUyGGY=
azure_storage_connectionstring: DefaultEndpointsProtocol=https;AccountName=pipelinestorageazu;AccountKey=J6QLmIIoKg5qG9LM5OeUS4yGjzS77NMTnaTCLk3ayT/iiioE++OaNHi5OMvgjgnm3uZsonfM6Z4L+AStnCUmFQ==;EndpointSuffix=core.windows.net
b: 16
complete: 'True'
container_name: container
density: 0.04187802201550127
max_runs: 5
mode: ml
n: 4
points: 8000
queue_name: queue
r: 1
radius_factor: 0.01
s: 6
save_folder: download
slice_variations: 0
wait_time: 60
