#feature search
feature_radius: 2.4
forest_size: 10

#messaging
max_runs: 1
wait_time: 10
azure_messaging_connectionstring: Endpoint=sb://messagingpipeline.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=yd4DxLLNyHoYZQGQ/RmYP3uZvDggm1RmBQuI7WUyGGY=
queue_name: queue

#storage
azure_storage_connectionstring: DefaultEndpointsProtocol=https;AccountName=pipelinestorageazu;AccountKey=J6QLmIIoKg5qG9LM5OeUS4yGjzS77NMTnaTCLk3ayT/iiioE++OaNHi5OMvgjgnm3uZsonfM6Z4L+AStnCUmFQ==;EndpointSuffix=core.windows.net
container_name: container
save_folder: download
upload_folder: upload